Avoid stopping the bridge if there was an exception during the startup of the brigde. Doing so was causing
abb@e6510:~/dvp/sslcaudit$ bin/sslcaudit -g
Traceback (most recent call last):
  File "bin/../sslcaudit/core/SSLCAuditGUI.py", line 215, in startStopAudit
    self._startAudit()
  File "bin/../sslcaudit/core/SSLCAuditGUI.py", line 246, in _startAudit
    self.bridge.stop()
  File "bin/../sslcaudit/core/SSLCAuditGUI.py", line 85, in stop
    self.controller.stop()
AttributeError: 'SSLCAuditQtBridge' object has no attribute 'controller'